#!/usr/bin/env python3
# SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me>
# SPDX-License-Identifier: GPL-3.0-or-later
"""Design token generator: resolves theme refs and emits platform outputs.

Reads tokens.json (layout/spacing tokens) and themes.json (color themes with
primitives + semantic references), resolves {ref} references, and emits:

  generated/themes.json       — resolved flat format (backward-compatible v1)
  generated/tokens.css        — CSS custom properties
  generated/tokens_ansi.json  — TUI ANSI color mapping

Usage:
    python3 scripts/generate.py
    python3 scripts/generate.py --out-dir custom/output
"""

import argparse
import json
import re
import sys
from pathlib import Path

REF_PATTERN = re.compile(r"^\{([a-zA-Z][a-zA-Z0-9-]*)\}$")

# Semantic color → closest ANSI 256 mapping strategy:
# We map semantic roles to ANSI color indices for TUI rendering.
ANSI_ROLE_MAP = {
    "bg-primary": "0",      # background
    "bg-secondary": "0",    # background variant
    "bg-tertiary": "8",     # bright black (gray)
    "text-primary": "15",   # bright white
    "text-secondary": "7",  # white (dim)
    "accent": "12",         # bright blue
    "accent-dark": "4",     # blue
    "success": "10",        # bright green
    "error": "9",           # bright red
    "warning": "11",        # bright yellow
    "border": "8",          # bright black (gray)
}


def resolve_theme(theme: dict) -> dict[str, str]:
    """Resolve all semantic {ref} references to hex values via primitives.

    Returns a flat dict of semantic-key -> hex-value.
    Raises ValueError on missing or invalid references.
    """
    primitives = theme["primitives"]
    semantic = theme["semantic"]
    resolved = {}

    for key, ref in semantic.items():
        m = REF_PATTERN.match(ref)
        if not m:
            raise ValueError(
                f"Theme '{theme['id']}': semantic.{key} has invalid "
                f"reference format '{ref}' (expected {{name}})"
            )
        prim_name = m.group(1)
        if prim_name not in primitives:
            raise ValueError(
                f"Theme '{theme['id']}': semantic.{key} references "
                f"missing primitive '{prim_name}'"
            )
        resolved[key] = primitives[prim_name]

    return resolved


def hex_to_rgb(hex_color: str) -> tuple[int, int, int]:
    """Convert #RRGGBB to (R, G, B) tuple."""
    h = hex_color.lstrip("#")
    return (int(h[0:2], 16), int(h[2:4], 16), int(h[4:6], 16))


def find_closest_ansi256(hex_color: str) -> int:
    """Find the closest ANSI 256 color index for a hex color.

    Uses the 6x6x6 color cube (indices 16-231) plus grayscale ramp (232-255).
    """
    r, g, b = hex_to_rgb(hex_color)

    # Check 6x6x6 cube (indices 16-231)
    # Each axis: 0, 95, 135, 175, 215, 255 → steps 0-5
    cube_steps = [0, 95, 135, 175, 215, 255]

    def nearest_cube(val: int) -> int:
        best = 0
        best_dist = abs(val - cube_steps[0])
        for i, step in enumerate(cube_steps[1:], 1):
            dist = abs(val - step)
            if dist < best_dist:
                best = i
                best_dist = dist
        return best

    ri, gi, bi = nearest_cube(r), nearest_cube(g), nearest_cube(b)
    cube_idx = 16 + 36 * ri + 6 * gi + bi
    cube_r, cube_g, cube_b = cube_steps[ri], cube_steps[gi], cube_steps[bi]
    cube_dist = (r - cube_r) ** 2 + (g - cube_g) ** 2 + (b - cube_b) ** 2

    # Check grayscale ramp (indices 232-255): 8, 18, 28, ..., 238
    gray_val = (r + g + b) // 3
    gray_idx = max(0, min(23, (gray_val - 8 + 5) // 10))
    gray_level = 8 + 10 * gray_idx
    gray_dist = (r - gray_level) ** 2 + (g - gray_level) ** 2 + (b - gray_level) ** 2

    if gray_dist < cube_dist:
        return 232 + gray_idx
    return cube_idx


def generate_flat_themes(themes: list[dict]) -> list[dict]:
    """Generate backward-compatible flat themes (v1 format)."""
    flat = []
    for theme in themes:
        resolved = resolve_theme(theme)
        entry = {
            "id": theme["id"],
            "name": theme["name"],
            "version": theme["version"],
            "mode": theme["mode"],
        }
        if "author" in theme:
            entry["author"] = theme["author"]
        if "license" in theme:
            entry["license"] = theme["license"]
        if "source" in theme:
            entry["source"] = theme["source"]
        entry["colors"] = resolved
        flat.append(entry)
    return flat


def generate_css(tokens: dict, themes: list[dict]) -> str:
    """Generate CSS custom properties for tokens and themes."""
    lines = [
        "/* Auto-generated by scripts/generate.py — do not edit */",
        # REUSE-IgnoreStart
        "/* SPDX-FileCopyrightText: 2026 Mattia Egloff <mattia.egloff@pm.me> */",
        "/* SPDX-License-Identifier: GPL-3.0-or-later */",
        # REUSE-IgnoreEnd
        "",
        "/* === Layout tokens === */",
        ":root {",
    ]

    # Spacing tokens
    if "spacing" in tokens:
        for key, val in tokens["spacing"].items():
            lines.append(f"  --spacing-{key}: {val}px;")

    if "spacing_direction" in tokens:
        for key, val in tokens["spacing_direction"].items():
            css_key = key.replace("_", "-")
            lines.append(f"  --spacing-{css_key}: {val}px;")

    # Typography
    if "typography" in tokens:
        for key, val in tokens["typography"].items():
            css_key = key.replace("_", "-")
            lines.append(f"  --{css_key}: {val}px;")

    # Border radius
    if "border_radius" in tokens:
        for key, val in tokens["border_radius"].items():
            lines.append(f"  --radius-{key}: {val}px;")

    # Touch target
    if "touch_target" in tokens:
        for key, val in tokens["touch_target"].items():
            lines.append(f"  --touch-target-{key}: {val}px;")

    # Motion
    if "motion" in tokens:
        for key, val in tokens["motion"].items():
            css_key = key.replace("_", "-").replace("-ms", "")
            lines.append(f"  --motion-{css_key}: {val}ms;")

    lines.append("}")
    lines.append("")

    # Theme color classes
    lines.append("/* === Theme colors === */")
    for theme in themes:
        resolved = resolve_theme(theme)
        selector = f'[data-theme="{theme["id"]}"]'
        lines.append(f"{selector} {{")
        for key, val in resolved.items():
            lines.append(f"  --color-{key}: {val};")
        lines.append("}")
        lines.append("")

    return "\n".join(lines)


def generate_ansi(themes: list[dict]) -> list[dict]:
    """Generate ANSI 256 color mapping for TUI rendering."""
    ansi_themes = []
    for theme in themes:
        resolved = resolve_theme(theme)
        ansi_colors = {}
        for key, hex_val in resolved.items():
            ansi_colors[key] = {
                "hex": hex_val,
                "ansi256": find_closest_ansi256(hex_val),
                "ansi_base": ANSI_ROLE_MAP.get(key, "7"),
            }
        ansi_themes.append({
            "id": theme["id"],
            "name": theme["name"],
            "mode": theme["mode"],
            "colors": ansi_colors,
        })
    return ansi_themes


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate design token outputs")
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=None,
        help="Output directory (default: generated/ in repo root)",
    )
    args = parser.parse_args()

    repo_root = Path(__file__).parent.parent
    out_dir = args.out_dir or (repo_root / "generated")

    tokens_path = repo_root / "tokens.json"
    themes_path = repo_root / "themes.json"

    # Load inputs
    if not tokens_path.exists():
        print(f"ERROR: {tokens_path} not found")
        return 1
    if not themes_path.exists():
        print(f"ERROR: {themes_path} not found")
        return 1

    with open(tokens_path) as f:
        tokens = json.load(f)
    with open(themes_path) as f:
        themes = json.load(f)

    print(f"Loaded {len(themes)} themes, tokens v{tokens.get('version', '?')}")

    # Validate all refs resolve before generating anything
    for theme in themes:
        try:
            resolve_theme(theme)
        except ValueError as e:
            print(f"ERROR: {e}")
            return 1

    # Create output directory
    out_dir.mkdir(parents=True, exist_ok=True)

    # Generate flat themes (backward-compatible)
    flat_themes = generate_flat_themes(themes)
    flat_path = out_dir / "themes.json"
    with open(flat_path, "w") as f:
        json.dump(flat_themes, f, indent=2)
        f.write("\n")
    print(f"  -> {flat_path} ({len(flat_themes)} themes)")

    # Generate CSS
    css_content = generate_css(tokens, themes)
    css_path = out_dir / "tokens.css"
    with open(css_path, "w") as f:
        f.write(css_content)
    print(f"  -> {css_path}")

    # Generate ANSI mapping
    ansi_themes = generate_ansi(themes)
    ansi_path = out_dir / "tokens_ansi.json"
    with open(ansi_path, "w") as f:
        json.dump(ansi_themes, f, indent=2)
        f.write("\n")
    print(f"  -> {ansi_path} ({len(ansi_themes)} themes)")

    print("Done.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
